name: NoPSInTrialChamber
version: 1.0
main: com.yourname.nops.NoPSInTrialChamber
api-version: '1.21'
depend: [WorldGuard]
softdepend: [ProtectionStones]
description: Запрещает приваты рядом с Trial Chambers
